/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#894e46",
        "primary-container": "#c9847a",
        "primary-fixed": "#ffdad5",
        "primary-fixed-dim": "#ffb4a9",
        "on-primary": "#ffffff",
        "on-primary-container": "#4f201a",
        "on-primary-fixed": "#370d09",
        "on-primary-fixed-variant": "#6d3730",
        "inverse-primary": "#ffb4a9",
        "secondary": "#745a27",
        "secondary-container": "#fedb9b",
        "secondary-fixed": "#ffdea4",
        "secondary-fixed-dim": "#e4c285",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#795f2b",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5a4312",
        "tertiary": "#705953",
        "tertiary-container": "#aa9089",
        "tertiary-fixed": "#fadcd4",
        "tertiary-fixed-dim": "#ddc0b8",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#3c2a25",
        "on-tertiary-fixed": "#281813",
        "on-tertiary-fixed-variant": "#56423c",
        "background": "#fdf8f5",
        "surface": "#fdf8f5",
        "surface-dim": "#ded9d6",
        "surface-bright": "#fdf8f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f3f0",
        "surface-container": "#f2edea",
        "surface-container-high": "#ece7e4",
        "surface-container-highest": "#e6e2df",
        "surface-variant": "#e6e2df",
        "surface-tint": "#894e46",
        "on-surface": "#1c1b1a",
        "on-surface-variant": "#524341",
        "on-background": "#1c1b1a",
        "inverse-surface": "#32302e",
        "inverse-on-surface": "#f5f0ed",
        "outline": "#857370",
        "outline-variant": "#d7c2be",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "cormorant": ["Cormorant Garamond", "serif"],
        "playfair": ["Playfair Display", "serif"],
        "dmsans": ["DM Sans", "sans-serif"],
        "serif-editorial": ["Cormorant Garamond", "serif"],
        "serif-authority": ["Playfair Display", "serif"],
        "sans-ui": ["DM Sans", "sans-serif"],
        "authority": ["Playfair Display", "serif"],
        "editorial": ["Cormorant Garamond", "serif"],
        "serif": ["Cormorant Garamond", "serif"],
        "display": ["Playfair Display", "serif"],
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
